CREATE TABLE IF NOT EXISTS week09users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    uuid TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    username TEXT NOT NULL,
    bio TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS week09posts (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    msg TEXT NOT NULL,
    user_id INT REFERENCES week09users(id) NOT NULL
);
CREATE TABLE IF NOT EXISTS week09comments (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    msg TEXT NOT NULL,
    post_id INT REFERENCES week09posts(id) NOT NULL,
    user_id INT REFERENCES week09users(id) NOT NULL
);